import * as Icons from "lucide-react";

// Name → Lucide icon component for task icons.
// Keep in sync with the icon names the server auto-assigns (see
// server/src/modules/tasks/icon-catalog.js). Add icon-name => component here to
// make it available in the picker.
export const iconComponents = {
  trash: Icons.Trash,
  shirt: Icons.Shirt,
  sparkles: Icons.Sparkles,
  vacuum: Icons.RobotVacuum,
  "paw-print": Icons.PawPrint,
  utensils: Icons.Utensils,
  "cooking-pot": Icons.CookingPot,
  "shopping-cart": Icons.ShoppingCart,
  "shower-head": Icons.ShowerHead,
  "book-open": Icons.BookOpen,
  music: Icons.Music,
  dumbbell: Icons.Dumbbell,
  puzzle: Icons.Puzzle,
  smartphone: Icons.Smartphone,
  bed: Icons.Bed,
  shovel: Icons.Shovel,
  wrench: Icons.Wrench,
  paintbrush: Icons.Paintbrush,
  car: Icons.Car,
  bike: Icons.Bike,
  wallet: Icons.Wallet,
  pill: Icons.Pill,
  gift: Icons.Gift,
  "hand-helping": Icons.HandHelping,
  footprints: Icons.Footprints,
  footsteps: Icons.Footprints,
  book: Icons.Book,
  package: Icons.Package,
  phone: Icons.Phone,
  "layout-grid": Icons.LayoutGrid,
  // Additional searchable choices
  star: Icons.Star,
  heart: Icons.Heart,
  leaf: Icons.Leaf,
  sun: Icons.Sun,
  moon: Icons.Moon,
  briefcase: Icons.Briefcase,
  "dollar-sign": Icons.DollarSign,
  clock: Icons.Clock,
  calendar: Icons.Calendar,
  home: Icons.Home,
  user: Icons.User,
  users: Icons.Users,
  key: Icons.Key,
  lock: Icons.Lock,
  "list-checks": Icons.ListChecks,
};

// Searchable catalog for the picker: label keywords -> icon name
export const iconCatalog = [
  ["trash", "trash, rubbish, garbage, recycle, bin, compost, take out"],
  ["shirt", "laundry, clothes, wash, fold, dishwasher, dishes, iron"],
  ["sparkles", "clean, tidy, organize, dust, sparkle, shine"],
  ["vacuum", "vacuum, hoover, carpet"],
  ["paw-print", "pet, dog, cat, feed, walk dog, animal"],
  ["utensils", "eat, food, meal, meal plan, cooking, dining"],
  ["cooking-pot", "cook, dinner, lunch, breakfast, bake, pot"],
  ["shopping-cart", "shopping, groceries, grocery, buy, store, errand, market"],
  ["shower-head", "shower, bath, bathroom, hygiene, wash, brush teeth"],
  ["book-open", "read, reading, book, homework, study, library"],
  ["music", "music, piano, guitar, practice, instrument, band"],
  ["dumbbell", "sport, exercise, gym, workout, soccer, swim, run, practice"],
  ["puzzle", "play, toy, lego, craft, game, puzzle, fun"],
  ["smartphone", "phone, call, text, message, screen, device"],
  ["bed", "bed, sleep, nap, wake, make bed, pyjamas"],
  ["shovel", "garden, yard, lawn, plant, mow, dig, weed, compost"],
  ["wrench", "fix, repair, build, tools, maintenance, diy, plumbing"],
  ["paintbrush", "paint, art, draw, color, decorating"],
  ["car", "car, vehicle, drive, garage, commute"],
  ["bike", "bike, bicycle, cycle, ride"],
  ["wallet", "money, allowance, budget, bank, save, pay"],
  ["pill", "medicine, pill, vitamin, medication, health"],
  ["gift", "birthday, present, gift, party, celebrate"],
  ["hand-helping", "help, assist, chores, volunteer"],
  ["footprints", "walk, run, outside, exercise"],
  ["book", "book, read, library, study"],
  ["package", "package, parcel, mail, delivery, post"],
  ["phone", "phone, call, contact"],
  ["layout-grid", "organize, room, bedroom, setup, arrange"],
  ["star", "star, favorite, priority, top"],
  ["heart", "heart, love, favorite"],
  ["leaf", "leaf, plants, nature, garden, environment"],
  ["sun", "sun, morning, daylight, outside"],
  ["moon", "moon, night, bedtime"],
  ["briefcase", "work, job, office, business"],
  ["dollar-sign", "money, budget, allowance, finance"],
  ["clock", "time, schedule, reminder, appointment"],
  ["calendar", "calendar, date, event, schedule"],
  ["home", "home, house, chore around the house"],
  ["user", "person, one person, solo"],
  ["users", "people, family, group, everyone"],
  ["key", "key, unlock, security"],
  ["lock", "lock, secure, safety"],
  ["list-checks", "task, checklist, to-do, errand"],
];

export function resolveIcon(name) {
  return iconComponents[name] || Icons.CheckCircle2;
}