// Regenerates src/db/d1-schema.ts from the drizzle migration SQL directory.
// The Worker has no fs, so it applies the same statement list from an embedded
// module instead of reading drizzle/*.sql at runtime; this keeps the worker,
// the container, and the suite on the single generated schema.
//
// Usage: npx tsx scripts/gen-d1-schema.ts

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = pathDirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

async function run() {
  const dir = join(repoRoot, "drizzle");
  const files = (await readdir(dir)).filter((f) => f.endsWith(".sql")).sort();
  const parts = await Promise.all(files.map((f) => readFile(join(dir, f), "utf8")));
  const text = parts.join("\n").trim();

  const out = [
    "// GENERATED by scripts/gen-d1-schema.ts — do not edit by hand.",
    "// Run `npm run db:gen-schema` after `npm run db:generate` to refresh it.",
    "//",
    "// The Cloudflare Worker (which has no fs) applies exactly the same",
    "// drizzle-generated migration statements as the container and the test",
    "// suite, applied through core/migrations.ts#migrationStatementsFromText.",
    "",
    "export const D1_SCHEMA = " + JSON.stringify(text) + ";",
    "",
  ];
  await writeFile(join(repoRoot, "src", "db", "d1-schema.ts"), out.join("\n"));
  console.log(`d1-schema.ts written (${text.length} chars from ${files.join(", ")})`);
}

function pathDirname(p) {
  let i = p.lastIndexOf("/");
  if (i === -1) i = p.lastIndexOf("\\");
  return p.slice(0, i);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});